begin;

create table if not exists public.local_horarios (
  id bigint generated by default as identity primary key,
  local_id bigint not null references public.locales(id) on delete cascade,
  dia_semana smallint not null,
  abierto boolean not null default true,
  hora_apertura time without time zone,
  hora_cierre time without time zone,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  constraint ck_local_horarios_dia check (dia_semana between 1 and 7),
  constraint ck_local_horarios_rango check (
    abierto = false
    or (hora_apertura is not null and hora_cierre is not null and hora_apertura < hora_cierre)
  ),
  constraint uq_local_horarios_local_dia unique(local_id,dia_semana)
);

create index if not exists ix_local_horarios_local
  on public.local_horarios(local_id,dia_semana);

grant select, insert, update, delete on public.local_horarios to anon, authenticated;
grant usage, select on sequence public.local_horarios_id_seq to anon, authenticated;

commit;
