begin;

create table if not exists public.encargada_semana_tipo (
  id bigint generated by default as identity primary key,
  local_id bigint not null references public.locales(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  dia_semana smallint not null,
  tipo_semana text not null default 'todas',
  hora_desde time without time zone not null,
  hora_hasta time without time zone not null,
  observacion text,
  actualizado_por_user_id bigint references public.users(id) on delete set null,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  constraint ck_encargada_semana_tipo_dia check (dia_semana between 1 and 7),
  constraint ck_encargada_semana_tipo_tipo check (tipo_semana in ('todas','a','b')),
  constraint ck_encargada_semana_tipo_horas check (hora_desde < hora_hasta),
  constraint uq_encargada_semana_tipo unique(local_id,user_id,dia_semana,tipo_semana)
);

create index if not exists ix_encargada_semana_tipo_local
  on public.encargada_semana_tipo(local_id,dia_semana,user_id);

comment on table public.encargada_semana_tipo is
  'Plantilla semanal habitual de cobertura de encargadas por local. tipo_semana permite reglas generales o alternancia A/B.';

grant select, insert, update, delete on public.encargada_semana_tipo to anon, authenticated;
grant usage, select on sequence public.encargada_semana_tipo_id_seq to anon, authenticated;

commit;
