begin;

create table if not exists public.encargada_planificacion_config (
  local_id bigint primary key references public.locales(id) on delete cascade,
  fecha_referencia_a date not null,
  actualizado_por_user_id bigint references public.users(id) on delete set null,
  actualizado_en timestamptz not null default now()
);

comment on table public.encargada_planificacion_config is
  'Configuración por local para alternar automáticamente semanas A/B de encargadas.';

create table if not exists public.encargada_planificacion (
  id bigint generated by default as identity primary key,
  local_id bigint not null references public.locales(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  fecha date not null,
  hora_desde time without time zone not null,
  hora_hasta time without time zone not null,
  estado text not null default 'confirmado',
  origen text not null default 'semana_tipo',
  semana_tipo text,
  observacion text,
  reemplaza_user_id bigint references public.users(id) on delete set null,
  confirmado_por_user_id bigint references public.users(id) on delete set null,
  confirmado_en timestamptz,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now(),
  constraint ck_encargada_planificacion_horas check (hora_desde < hora_hasta),
  constraint ck_encargada_planificacion_estado check (estado in ('confirmado','modificado')),
  constraint ck_encargada_planificacion_origen check (origen in ('semana_tipo','manual')),
  constraint ck_encargada_planificacion_semana check (semana_tipo is null or semana_tipo in ('a','b')),
  constraint uq_encargada_planificacion unique(local_id,user_id,fecha)
);

create index if not exists ix_encargada_planificacion_local_fecha
  on public.encargada_planificacion(local_id,fecha,user_id);

comment on table public.encargada_planificacion is
  'Snapshot confirmado de la planificación de encargadas. Inicialmente se genera desde Semana Tipo; luego admite modificaciones manuales.';

grant select, insert, update, delete on public.encargada_planificacion_config to anon, authenticated;
grant select, insert, update, delete on public.encargada_planificacion to anon, authenticated;
grant usage, select on sequence public.encargada_planificacion_id_seq to anon, authenticated;

commit;
